### ISSUE TITLE
no angler token for exodor fish

### ISSUE THREAD

**Issue by themindi** [Risenio/fish-reference#1]
hi there, just a current note. fishing in exodor doesn't give angler token (anymore?).
just started playing like 1-2 months ago, so don't know what it was earlier.

**Comment by Risenio** [comment]
Hello.

The information which was added here is 100% accurate, by the time and patch they were added.

Surely there some changes has occurred since then.
E.g. Fishing in Gameforge's version of tera gave 0 gold as sale value for all kind of fishes, maybe they reverted that back now.
Same goes for the change regarding Angler tokens, might have reduced, or removed anglers for low-tier fishes, I'll take a look and update the list once I get information regarding that.

Thanks for taking the time to inform me that this list needs updating.

**Comment by Risenio** [comment]
Should be fixed now, corrected all values after confirming that none of Exodor fish types give Angler tokens anymore.

Closing as resolved.
